Throwable 클래스와 예외처리의 책임 전가.

예외 처리의 최상위 클래스
java.lang.Throwable

이 클래스에는 예외의 정보를 알 수 있는 메소드가 정의되어 있다.

public String getMessage()  -> 예외의 원인을 담고 있는 문자열을 반환.
public void printStackTrace() ->  예외가 발생한 위치와 호출된 메소드의 정보를 출력 (getMessage()도 같이 출력함)

프로그래머가 예외 처리를 하지 않으면 그 책임이 넘어가는데 그 끝은 main이다.


public class ExceptionMessage {
	public static void md1(int n)
	{
		md2(n,0);
	}
	public static void md2(int n1,int n2)
	{
		int r = n1 / n2;
	}
	public static void main(String[] args)
	{
		try {
			md1(3);
		}
		catch(Throwable e)
		{
			e.printStackTrace();
		}
	}
}

실제 넘어오는 예외는 Throwable이 아니다. 그러나 모든 예외 클래스는 Throwable을 상속하므로 위와 같이 처리할 수 있다.(좋지 않음)


예외클래스의 구분

예외클래스의 최상위 클래스 Throwable 클래스는 세 부류로 나뉘는데
1. Error 클래스를 상속하는 예외 클래스    
2. Exception 클래스를 상속하는 예외 클래스
3. RuntimeExceeption 클래스를 상속하는 예외 클래스  -> Exception 클래스를 상속 한다.

Error 클래스를 상속하는 예외는 처리의 대상이 아니다. 바꾸어 말하면 처리할 수 있는 예외가 아니다. 그냥 냅둬야함.

RuntimeException 클래스를 상속하는 예외는 앞서 보였던 모든 예외 클래스가 이 예외에 해당한다.(코드를 고쳐야하는 예외)

ArithmeticException
ClassCastException
IndexOutofBoundsException
NegativeArraySizeException
NullPointerException
ArrayStoreException
위 예외 대부분 프로그래머가 예외처리를 하지 않는다.  ( 예외의 처리는 선택 )

Exception 클래스를 상속하는 예외는 RuntimeException 예외 클래스 부류를 제외한 것이다.


Exception 클래스를 상속하는 예외처리

java.io.IOException

import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.Files;
import java.io.BufferedWriter;
import java.io.IOException;


public class IOExceptionCase {
	public static void main(String[] args)
	{
		Path file = Paths.get("C:\\JavaStudy\\Simple.txt");
		BufferedWriter writer = null;
		
		try {
			writer = Files.newBufferedWriter(file);
			writer.write('A');
			writer.write('Z');
			
			if(writer != null)
			{
				writer.close();
			}
		}
		catch(IOException e)
		{
			e.printStackTrace();
		}
	}
}
Exception 클래스를 상속하는 예외는 try~catch문으로 처리하거나 다른 영역으로 넘긴다고 반드시 명시해야한다.
public class IOExceptionCase {
	public static void main(String[] args)
	{
		try {
			md1();
		}
		catch(IOException e)
		{
			e.printStackTrace();
		}
	}
	public static void md1() throws IOException   // IOException 예외 넘긴다고 명시
	{
		md2();
	}
	public static void md2() throws IOException   // IOException 예외 넘긴다고 명시
	{
		Path file = Paths.get("C:\\JavaStudy\\Simple.txt");
		BufferedWriter writer = null;
		
		writer = Files.newBufferedWriter(file);
			writer.write('A');
			writer.write('Z');
			writer.write('C');
			
			if(writer != null)
			{
				writer.close();
			}
	}
}
throws로 둘 이상 예외에 대해 처리를 넘긴다는 표시를 할 수 있다
public void simpleWrite() throws IOException, IndexOutofBoundsException{....} 

